package sop_corba.ControladorAlertaIntPackage;


/**
* sop_corba/ControladorAlertaIntPackage/ListComprasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 06:46:06 PM COT
*/

public final class ListComprasHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.ControladorAlertaIntPackage.CompraDTO value[] = null;

  public ListComprasHolder ()
  {
  }

  public ListComprasHolder (sop_corba.ControladorAlertaIntPackage.CompraDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.ControladorAlertaIntPackage.ListComprasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.ControladorAlertaIntPackage.ListComprasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.ControladorAlertaIntPackage.ListComprasHelper.type ();
  }

}
