package sop_corba.ControladorAlertaIntPackage;


/**
* sop_corba/ControladorAlertaIntPackage/AlertaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 06:46:06 PM COT
*/

public final class AlertaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public long codigoAlerta = (long)0;
  public long idComprador = (long)0;
  public sop_corba.ControladorAlertaIntPackage.CompraDTO compras[] = null;
  public double valorAcumulado = (double)0;

  public AlertaDTO ()
  {
  } // ctor

  public AlertaDTO (long _codigoAlerta, long _idComprador, sop_corba.ControladorAlertaIntPackage.CompraDTO[] _compras, double _valorAcumulado)
  {
    codigoAlerta = _codigoAlerta;
    idComprador = _idComprador;
    compras = _compras;
    valorAcumulado = _valorAcumulado;
  } // ctor

} // class AlertaDTO
