package sop_corba.ControladorAlertaIntPackage;


/**
* sop_corba/ControladorAlertaIntPackage/CompraDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 06:46:06 PM COT
*/

abstract public class CompraDTOHelper
{
  private static String  _id = "IDL:sop_corba/ControladorAlertaInt/CompraDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.ControladorAlertaIntPackage.CompraDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.ControladorAlertaIntPackage.CompraDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "codigoCompra",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "idComprador",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "tipoIdentificacion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[3] = new org.omg.CORBA.StructMember (
            "valor",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "lugarCompra",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "fecha",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[6] = new org.omg.CORBA.StructMember (
            "idEmpresa",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.ControladorAlertaIntPackage.CompraDTOHelper.id (), "CompraDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.ControladorAlertaIntPackage.CompraDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.ControladorAlertaIntPackage.CompraDTO value = new sop_corba.ControladorAlertaIntPackage.CompraDTO ();
    value.codigoCompra = istream.read_longlong ();
    value.idComprador = istream.read_longlong ();
    value.tipoIdentificacion = istream.read_string ();
    value.valor = istream.read_double ();
    value.lugarCompra = istream.read_string ();
    value.fecha = istream.read_string ();
    value.idEmpresa = istream.read_longlong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.ControladorAlertaIntPackage.CompraDTO value)
  {
    ostream.write_longlong (value.codigoCompra);
    ostream.write_longlong (value.idComprador);
    ostream.write_string (value.tipoIdentificacion);
    ostream.write_double (value.valor);
    ostream.write_string (value.lugarCompra);
    ostream.write_string (value.fecha);
    ostream.write_longlong (value.idEmpresa);
  }

}
