package sop_corba.ControladorAlertaIntPackage;


/**
* sop_corba/ControladorAlertaIntPackage/CompraDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 06:46:06 PM COT
*/

public final class CompraDTO implements org.omg.CORBA.portable.IDLEntity
{
  public long codigoCompra = (long)0;
  public long idComprador = (long)0;
  public String tipoIdentificacion = null;
  public double valor = (double)0;
  public String lugarCompra = null;
  public String fecha = null;
  public long idEmpresa = (long)0;

  public CompraDTO ()
  {
  } // ctor

  public CompraDTO (long _codigoCompra, long _idComprador, String _tipoIdentificacion, double _valor, String _lugarCompra, String _fecha, long _idEmpresa)
  {
    codigoCompra = _codigoCompra;
    idComprador = _idComprador;
    tipoIdentificacion = _tipoIdentificacion;
    valor = _valor;
    lugarCompra = _lugarCompra;
    fecha = _fecha;
    idEmpresa = _idEmpresa;
  } // ctor

} // class CompraDTO
