package sop_corba;


/**
* sop_corba/ControladorAlertaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 06:46:06 PM COT
*/

public interface ControladorAlertaIntOperations 
{
  boolean registrarAlerta (sop_corba.ControladorAlertaIntPackage.AlertaDTO objAlerta);
} // interface ControladorAlertaIntOperations
